### ISSUE TITLE
When toggling between DB versions connecting to the cache fails.

### ISSUE THREAD

**Issue by tom-englert** [Microsoft/CodeContracts#122]
The is a design flaw in the implementation of #80 / #97. If there are both DBs installed, we might end up toggling between both versions if we just use the one that connects first.
If then the file was e.g. generated with v12, and next time v11 connects faster, we end up with "failed to connect to the cache" again!

**Comment by SergeyTeplyakov** [comment]
Ouch! Will fix it.

**Comment by tom-englert** [comment]
Also this could break connecting to and explicit specified SqlServer - if LocalDB is connecting faster, this would always use LocalDB!

**Comment by tom-englert** [comment]
Fixed this in  #123
