### ISSUE TITLE
Postocondition doesn't work in async method, when using contract class for interface

### ISSUE THREAD

**Issue by Dennis-Petrov** [Microsoft/CodeContracts#142]
Hi. I'm migrating project from .NET 4 to 4.5.1, using VS 2013, and one of the reasons is to use `async`/`await`. Project widely uses code contracts, most of them are defined for interfaces or abstract classes (hence, there are number of contract classes).

Why this code:

    [ContractClass(typeof(IAContract))]
    interface IA
    {
        Task<int> FooAsync();
    }

    [ContractClassFor(typeof(IA))]
    abstract class IAContract : IA
    {
        // public async Task<int> FooAsync() doesn't help too
        public Task<int> FooAsync()
        {
            Contract.Ensures(Contract.Result<int>() > 0);
            throw new NotImplementedException();
        }
    }

    class A : IA
    {
        public async Task<int> FooAsync()
        {
            await Task.Delay(1000);
            return -1;
        }
    }

doesn't trigger `ContractException`, while this code does:

    class A
    {
        public async Task<int> FooAsync()
        {
            Contract.Ensures(Contract.Result<int>() > 0);
            await Task.Delay(1000);
            return -1;
        }
    }

?

**Comment by sharwell** [comment]
I would actually expect the following code to produce an error when attempting to rewrite the assembly:

    // public async Task<int> FooAsync() doesn't help too
    public Task<int> FooAsync()
    {
        Contract.Ensures(Contract.Result<int>() > 0);
        throw new NotImplementedException();
    }

This code uses `Contract.Result<int>` in a method that returns `Task<int>`. If the method was marked `async` it would be a bit different because you don't have access to the returned `Task`.

**Comment by Dennis-Petrov** [comment]
Well, it doesn't produce an error and successfully compiles. But anyway, if I'll change the signature of contract method to be `async`:

        public async Task<int> FooAsync()
        {
            Contract.Ensures(Contract.Result<int>() > 0);
            throw new NotImplementedException();
        }

or even this way (to avoid warning):

        public async Task<int> FooAsync()
        {
            Contract.Ensures(Contract.Result<int>() > 0);
            await Task.Yield();
            throw new NotImplementedException();
        }

the behavior won't change.

**Comment by SergeyTeplyakov** [comment]
@sharwell Actually, in async method you can reference the task result.

So following code is absolutely correct and lead to contract violation if the result is not 42:

```c#
public static async Task<int> FooAsync()
{
  Contract.Ensures(Contract.Result<int>() == 42);
  await Task.Delay(42);
  return 43;
}
```

Calling this code you'll get a contract exception (wrapped into `AggregateException`).

I'll take a look at current issue more closely..

@Dennis-Petrov: Dennis, just to make sure we're on the same page: in your last example, `FooAsync` method is an interface implemnetation or not? Because if not, then the behavior is correct: postconditions should be hold only for successful methods.

**Comment by SergeyTeplyakov** [comment]
@Dennis-Petrov I can confirm that there is an issue with rewriter.

Will work on the fix.

**Comment by SergeyTeplyakov** [comment]
Ok, I've found the root cause of an issue: it seems that ccrewrite can't detect async postcondition in the interface method that contains only async postconditions. 

Here is a short-term workaround:

```c#
[ContractClass(typeof(IAContract))]
interface IA
{
    Task<int> FooAsync();
}

[ContractClassFor(typeof(IA))]
abstract class IAContract : IA
{
    // public async Task<int> FooAsync() doesn't help too
    public Task<int> FooAsync()
    {
        Contract.Requires(true); // ugly, but help ccrewrite to find the contract block here
        Contract.Ensures(Contract.Result<int>() > 0);
        throw new NotImplementedException();
    }
}
```

**Comment by SergeyTeplyakov** [comment]
Found a bug. Will send a PR with a fix shortly.

**Comment by Dennis-Petrov** [comment]
Sergey, thanks for a quick answer. I'll try a workaround a bit later.  
Also, it would be great to check rewriting of abstract methods (when contract class is written for abstract class instead of interface). I've not tested this case yet...

**Comment by SergeyTeplyakov** [comment]
I alrmost sure that my future fix will work in both cases. (and I'll create unit tests for both cases any way).

**Comment by sharwell** [comment]
> So following code is absolutely correct and lead to contract violation if the result is not 42:

There is one *huge* difference between the method I wrote and the one you wrote: you used the keyword `async`. When you leave it out (as in my code), the return value in code is the task itself, not the task's result.

**Comment by SergeyTeplyakov** [comment]
@sharwell It is a *huge* difference for you and me, but ccrewrite will deal with both cases:)

Following code will fail with postcondition violation ;):

```c#
static Task<int> FooAsync()
{
    Contract.Ensures(Contract.Result<int>() == 42);

    return Task.FromResult(35);
}
```

On IL level there is no difference between `async` based TAP and regular TAP so ccrewrite treats both of them equally. And, I would say, this is very good behavior, becuase I would really surprise if one behavior would work, but another - don't.

**Comment by SergeyTeplyakov** [comment]
Fix is ready in #144.

**Comment by SergeyTeplyakov** [comment]
I want to clarify my comment:

> On IL level there is no difference between async based TAP and regular TAP so ccrewrite treats both of them equally. And, I would say, this is very good behavior, because I would really surprise if one behavior would work, but another - don't.

Of course there is a huge difference, but ccrewrite does not looks into method body to get the difference. It just treats all task-return method separately.

**Comment by SergeyTeplyakov** [comment]
Fixed.
