### ISSUE TITLE
Error opening any files in Visual Studio since update

### ISSUE THREAD

**Issue by Tydude4Christ** [Microsoft/CodeContracts#147]
I installed CodeContracts 1.9.10714.2 yesterday and now I'm getting the following error when trying to open any files in Visual Studio and there's no option to disable CodeContracts so I'm going to have to uninstall it for now.

"No exports were found that match the constraint:
ContractName
Microsoft.VisualStudio.Utilities.IContentTypeRegistryService
RequiredTypeIdentity
Microsoft.VisualStudio.Utilities.IContentTypeRegistryService"

**Comment by sharwell** [comment]
@Tydude4Christ thanks for reporting this. Can you include the version of Visual Studio you have installed as well? Thanks!

**Comment by Tydude4Christ** [comment]
I have Visual Studio 2013 Premium. Sorry I should have been more specific but I don't have the editor extensions installed, just the Code Contracts Tools.

**Comment by sharwell** [comment]
This is very interesting. There are no references to `IContentTypeRegistryService` in the entire Code Contracts code base, including the editor extensions.

**Comment by SergeyTeplyakov** [comment]
I'm trying to reproduce this issue.

@Tydude4Christ Did you have previous versions of CC installed? 

I tried latest version, but I had previous version installed. And I didn't face any issue with latest installed version.

**Comment by Tydude4Christ** [comment]
@sharwell 
Here's what I have installed, most came standard with visual studio.
![image](https://cloud.githubusercontent.com/assets/10929167/8750880/91f813f8-2c6f-11e5-823a-a2ec2e437494.png)

@SergeyTeplyakov
I had 1.7.11202.10 previously installed before updating to 1.9.10714.2.

What's weird is it didn't start happening until today. I didn't have issues yesterday.

**Comment by sharwell** [comment]
It looks like the wrong version of the Code Contracts tools is installed or registered in Visual Studio. Can you try the following:

1. Close all running instances of Visual Studio
1. Uninstall all versions of Code Contracts via Control Panel
1. Open Visual Studio and verify that Code Contracts Tools is not listed
1. Install the latest version of Code Contracts Tools
  * At this point, Visual Studio's Extension Manager should list the correct version next to Code Contracts Tools

**Comment by SergeyTeplyakov** [comment]
> I had 1.7.11202.10 previously installed before updating to 1.9.10714.2.

> What's weird is it didn't start happening until today. I didn't have issues yesterday.

That's really weird. Did you rebooted your PC or install any other VS Extensions? This is really weird...

**Comment by Tydude4Christ** [comment]
@SergeyTeplyakov
I rebooted yesterday and it was working fine after that.

@sharwell 
Yeah, I had the same issue as https://github.com/Microsoft/CodeContracts/issues/7.

I uninstalled Code Contracts, fixed it from showing in the extensions, and am now reinstalling 1.9.10714.2, hopefully that fixes it.

**Comment by Tydude4Christ** [comment]
It finished installing and I'm able to open files in Visual Studio again. If it happens again I'll report back.
