### ISSUE TITLE
1.9.10701.2 MSI installer misplaces Visual Studio extensions

### ISSUE THREAD

**Issue by yaakov-h** [Microsoft/CodeContracts#163]
On a clean installation of Windows 10 Preview (10074) with Visual Studio 2015 RTM, the installer creates files in the following locations:

* C:\VS10Root\Common7\IDE\Extensions\Microsoft\CodeContracts\1.9.10714.2
* C:\VS11Root\Common7\IDE\Extensions\Microsoft\CodeContracts\1.9.10714.2
* C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\CodeContracts\1.9.10714.2

I'm assuming the first two are because I don't have Visual Studio 2010 or 2012 installed.

I would think the installer should not install Visual Studio extensions if the corresponding Visual Studio version is not installed.

**Comment by sharwell** [comment]
Definitely a :bug:. Thank you for taking the time to report this. :smile:

**Comment by cremor** [comment]
Seems to be the same problem that I already reported as issue #8
