### ISSUE TITLE
Sql exceptions:  String or binary data would be truncated

### ISSUE THREAD

**Issue by ReverseBlade** [Microsoft/CodeContracts#165]
I am getting  below errors when running static cheker

CodeContracts: PISON.DataRepo: [cache] SqlCacheModel: SaveChanges failed: An error occurred while updating the entries. See the inner exception for details.
CodeContracts: PISON.DataRepo: validation error: The field Kind must be a string or array type with a maximum length of '100'.
CodeContracts: PISON.DataRepo: validation error: The field Kind must be a string or array type with a maximum length of '100'.
CodeContracts: PISON.DataRepo: validation error: The field Kind must be a string or array type with a maximum length of '100'.
CodeContracts: PISON.DataRepo: validation error: The field Kind must be a string or array type with a maximum length of '100'.
CodeContracts: PISON.DataRepo: Innner exception: An error occurred while updating the entries. See the inner exception for details.
CodeContracts: PISON.DataRepo: Innner exception: String or binary data would be truncated.

**Comment by jterry75** [comment]
I see this too. It appears from looking at the code that in SuggestionMap.cs

```cs
this.Property(t => t.Kind)
      .IsRequired()
      .HasMaxLength(100);
```

is not long enough for methods that have a prefixed namespace that is quite long. Can we increase the length of the requirement in the entity map and corresponding cache database to 400 which is the "method name" length requirement?
