### ISSUE TITLE
Using capturing precondition in async method in struct lead to invalid IL

### ISSUE THREAD

**Issue by SergeyTeplyakov** [Microsoft/CodeContracts#168]
This bug is related to the #157, but not similar.

Consider following code:

```c#
struct Foo
{
    public int Limit { get; set; }

    public Foo(int limit) : this()
    {
        Limit = 42;
    }

    public async Task<int> FooAsync()
    {
        Contract.Requires(Limit == 42);

        await Task.Delay(42);

        return 42;
    }
}
```

Running this code will lead to `InvalidProgramException` when preconditions are enabled.

CC version: 1.8+. This is not a regression, this stuff never worked properly.

Please note, the if the `Contract.Requires` will use arguments everything would be fine. Only when precondition is using `this` the app will fail.

**Comment by hubuk** [comment]
@SergeyTeplyakov Are you working on this?

**Comment by SergeyTeplyakov** [comment]
@hubuk At least not right now. I hope to merge pull requrests this week, so you can grab it.

**Comment by hubuk** [comment]
Grabbed
