### ISSUE TITLE
Code Contract Editor Extensions for VS 2012 crash on start

### ISSUE THREAD

**Issue by jterry75** [Microsoft/CodeContracts#17]
Every time I start Visual Studio with the "Code Contracts Editor Extensions VS2012" enabled it crashes on start and asks me to send the logs. I am using:

Microsoft Visual Studio Ultimate 2013
Version 12.0.31101.00 Update 4

Microsoft .NET Framework
Version 4.6.00031

Is there a more up-to-date version for VS 2013 that does not crash? I have not been able to locate it.

Thanks,
Justin

**Comment by hubuk** [comment]
Shall be fixed in PR #44.

**Comment by sharwell** [comment]
Fixed by #66.
