### ISSUE TITLE
CC1099: Contract extraction failed: async/iterator issue in async without await

### ISSUE THREAD

**Issue by mgaffigan** [Microsoft/CodeContracts#172]
I am getting the error `CC1099` on a particular method.  I have narrowed the method down to one specific change which will cause the failure.  The below sample compiled as a console application with rewriting enabled seems to reliably fail.

Error:
> EXEC : error CC1099: Contract extraction failed: async/iterator issue: In method EmptyAsyncTest.Program.Foo, assembly EmptyAsyncTest\EmptyAsyncTest\obj\Debug\EmptyAsyncTest.exe

Code:

    using System;
    using System.Threading.Tasks;

    namespace EmptyAsyncTest
    {
        class Program
        {
            static void Main(string[] args)
            {
            }

            async Task Foo()
            {
                if (DateTime.Now.Day == 0 && 1 == 2)
                {
                }
            }
        }
    }

The following variations do not trigger the bug:
 - Removing `async` and returning `Task.FromResult(false)`
 - Removing `&& 1 == 2`
 - Removing `DateTime.Now.Day == 0`
 - Adding `await Task.Delay(1)`

Environment:
VS 2015 CTP, Code Contracts 1.9.10714.2, Windows 8.1, Project is .Net 4.5, Only rewriting is enabled
Also repro'd by compiling fe3bf15c36923ebb833087d8c8781ce2ae60e6ce and running `foxtrot`.  Same output.

**Comment by SergeyTeplyakov** [comment]
grabbed.

**Comment by sharwell** [comment]
@mgaffigan This is a great bug report. Thanks for taking the time to find a simple way to reproduce the problem and explain the variants you tested. :smile:

**Comment by SergeyTeplyakov** [comment]
Investigation results:

1. This bug is only for VS2015
2. Only for async methods without awaits
3. Only for async methods without contracts

I'm running the tests right now for the fix.

**Comment by SergeyTeplyakov** [comment]
Created PR with a fix: #173.

**Comment by mgaffigan** [comment]
@SergeyTeplyakov, Thank you for the quick response.

**Comment by SergeyTeplyakov** [comment]
@mgaffigan You're welcome! And thanks a lot for great bug report!

**Comment by takinosaji** [comment]
Bug still presented. Got this error on such a code:

> public override async Task Meth(Int32 number)

**Comment by GreenKn1ght** [comment]
@takinosaji, are you use [this](https://github.com/Microsoft/CodeContracts/releases/tag/v1.10.10126.2) pre-release or latest?

**Comment by takinosaji** [comment]
@GreenKn1ght nope i am using latest.

**Comment by GreenKn1ght** [comment]
@takinosaji just asking because this fix not released yet =/

**Comment by NiceStepUp** [comment]
Adding `await` part to async is fixed this error. Thanks, guys and especially to Sergei Teplyakov! 

> _Investigation results:
> 
> 1. This bug is only for VS2015
> 2. Only for async methods without awaits
> 3. Only for async methods without contracts_
