### ISSUE TITLE
Impove string-contained code snippets

### ISSUE THREAD

**Issue by Dennis-Petrov** [Microsoft/CodeContracts#190]
`cresn`/`cesn` code snippets should generate `string` type name:

        Contract.Ensures(!string.IsNullOrEmpty(Contract.Result<string>()));
        Contract.Requires<ArgumentException>(!string.IsNullOrEmpty(arg));

instead of `String`:

        Contract.Ensures(!String.IsNullOrEmpty(Contract.Result<string>()));
        Contract.Requires<ArgumentException>(!String.IsNullOrEmpty(arg));

Also, something like `cresnw`/`cesnw` will be suitable:

        Contract.Ensures(!string.IsNullOrWhitespace(Contract.Result<string>()));
        Contract.Requires<ArgumentException>(!string.IsNullOrWhitespace(arg));

I know, that I could fix/add snippets by myself, but out-of-the-box always better :).

**Comment by sharwell** [comment]
I completely agree!

Want to try your hand at a pull request? The snippets are located [here](https://github.com/Microsoft/CodeContracts/tree/master/Microsoft.Research/ManagedContract.Setup/CSharpCodeSnippets).

**Comment by Dennis-Petrov** [comment]
Sure, I didn't know that I can add something here. :)

**Comment by Dennis-Petrov** [comment]
New snippets are included in RC.
