### ISSUE TITLE
Incorrect Identity version in extension.vsixmanifest 

### ISSUE THREAD

**Issue by ReverseBlade** [Microsoft/CodeContracts#195]
Someone forgot to correct the Identity Version in the extension.vsixmanifest file which still claims to be 1.8.10107.10 :-) (in a 1.9.10714.2 folder, very funny)

**Comment by sharwell** [comment]
Duplicate of #161. It will be fixed for the next release, although it may require a manual step during the next upgrade (it will be part of the release notes).

**Comment by ReverseBlade** [comment]
dup
