### ISSUE TITLE
Unhandled exception in cccheck

### ISSUE THREAD

**Issue by yaakov-h** [Microsoft/CodeContracts#198]
If I build `My.Redacted.Project.Name` with Visual Studio **2013**, Code Contracts 1.9.10714.2, it builds, rewrites and statically checks just fine.

If I build `My.Redacted.Project.Name` with Visual Studio **2015**, Code Contracts 1.9.10714.2, it builds, rewrites (I assume) fine, but then the static analysis crashes with the following error:

If I add `[ContractVerification(false)]` to the affected method, it crashes with the same error on another method, and another... I gave up ignoring after 3 affected methods, all of which are very normal and simple methods (e.g. the entire body is `throw new NotImplementedException();`).

	CodeContractsRunCodeAnalysisInternal:
	  CodeContracts: Task manager is unavailable (unable to run in background).
	  CodeContracts: My.Redacted.Project.Name: Run static contract analysis.
	  CodeContracts: My.Redacted.Project.Name: Time spent connecting to the cache: 00:00:01.1110440
	  CodeContracts: My.Redacted.Project.Name: Cache used: localhost
	  CodeContracts: My.Redacted.Project.Name: Internal error at method Method 2467 :  My.Redacted.Project.Name.ClassName.#ctor(System.Threading.Tasks.Task`1<System.Byte[]>)
	  CodeContracts: My.Redacted.Project.Name: Failed with uncaught exception: The given key was not present in the dictionary.
	  CodeContracts: My.Redacted.Project.Name: Stack trace:    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
	  CodeContracts: My.Redacted.Project.Name: \n   at Microsoft.Research.CodeAnalysis.Caching.CacheModelExtensions.GetAPC(OutcomeOrSuggestion this\, BijectiveMap`2 subroutineLocalIds)
	  CodeContracts: My.Redacted.Project.Name: \n   at Microsoft.Research.CodeAnalysis.Caching.CacheModelExtensions.GetWitness(Outcome this\, BijectiveMap`2 subroutineLocalIds)
	  CodeContracts: My.Redacted.Project.Name: \n   at Microsoft.Research.CodeAnalysis.CacheManager`11.ReplayMethodAnalysis(Method method\, MethodHashAttributeFlags mhAttrFlags\, Method methodModel\, InferredExpr`2 inferredExpr\, AnalysisStatistics& stats\, ContractDensity& contractDensity)
	  CodeContracts: My.Redacted.Project.Name: \n   at Microsoft.Research.CodeAnalysis.CacheManager`11.TryReplayAnalysisInternal(Method method\, Boolean trace\, AnalysisStatistics& stats\, ContractDensity& contractDensity\, ByteArray& hash)
	  CodeContracts: My.Redacted.Project.Name: \n   at Microsoft.Research.CodeAnalysis.CacheManager`11.TryReplayAnalysis(Method method\, Boolean trace\, AnalysisStatistics& stats\, ContractDensity& contractDensity\, ByteArray& hash)
	  CodeContracts: My.Redacted.Project.Name: \n   at Microsoft.Research.CodeAnalysis.Clousot.TypeBinder`9.AnalyzeMethodInternal2(Method method\, MethodAnalysisFlags analysisFlags\, IClassDriver`13& cdriver\, AnalysisStatistics& methodStats\, APC& entryPC)
	  CodeContracts: My.Redacted.Project.Name: \n   at Microsoft.Research.CodeAnalysis.Clousot.TypeBinder`9.AnalyzeMethodInternal(Method method\, MethodAnalysisFlags analysisFlags)
	  CodeContracts: My.Redacted.Project.Name: \n   at Microsoft.Research.CodeAnalysis.Clousot.TypeBinder`9.AnalyzeMethod(Method method)
	  CodeContracts: My.Redacted.Project.Name: \n   at Microsoft.Research.CodeAnalysis.Clousot.TypeBinder`9.DoWork(Int32 totalMethods\, Int32& progressChars\, Stopwatch assemblyStopWatch\, Method method)
	  CodeContracts: My.Redacted.Project.Name: \n   at Microsoft.Research.CodeAnalysis.Clousot.TypeBinder`9.AnalyzeMethodsInAssembly(Int32 totalMethods\, Int32 progressChars\, Stopwatch stopWatch)
	  CodeContracts: My.Redacted.Project.Name: \n   at Microsoft.Research.CodeAnalysis.Clousot.TypeBinder`9.AnalyzeAssemblyInternal(Int32 totalMethods\, Int32 progressChars\, Stopwatch stopWatch)
	  CodeContracts: My.Redacted.Project.Name: \n   at Microsoft.Research.CodeAnalysis.Clousot.TypeBinder`9.AnalyzeAssembly(Assembly assembly\, Set`1 assembliesUnderAnalysis)
	  CodeContracts: My.Redacted.Project.Name: \n   at Microsoft.Research.CodeAnalysis.Clousot.TypeBinder`9.InternalAnalyze()
	  CodeContracts: My.Redacted.Project.Name: \n   at Microsoft.Research.CodeAnalysis.Clousot.TypeBinder`9.Analyze()
	  CodeContracts: My.Redacted.Project.Name: 
	  CodeContracts: My.Redacted.Project.Name: Static contract analysis done.

I haven't been able to build a standalone repro case for this. It may be related to the size of the assembly, but that's just a guess.

I've managed to compile and statically check over 300 other assemblies in this project on VS2015 and Code Contracts 1.9.10714.2 as above.

Any tips for trying to debug this myself?

**Comment by fedotovalex** [comment]
From the call stack it appears it's related to caching, so I'd try disabling caching and see if it still reproduces. You may also want to try clearing the cache, which you can find in `%LOCALAPPDATA%\CodeContracts`.

As far as debugging goes, you want to build the CodeContracts.sln project and run the Clousot project (this is the internal name for cccheck). I usually just point it to the corressponding .rsp file of the project that's giving me trouble; you can find that file in `obj\{Configuration}\Decl`.

**Comment by yaakov-h** [comment]
Thanks. It took me a while to figure out if I needed Clousot or Clousot2.

Amongst other things, I tried creating a new release from master to see if any recent commits have fixed my issue, and the crash has gone away. That may be a side effect of a new version having a new cache database in SQL Server, but I'm not 100% sure yet.

**Comment by yaakov-h** [comment]
This isn't occurring anymore after dropping the cache database, so I'm closing this.
