### ISSUE TITLE
String.IndexOfAny contract incorrect

### ISSUE THREAD

**Issue by codespare** [Microsoft/CodeContracts#200]
Both the .NET 4.5 mscorlib contract reference assembly and \bin\Devlab9ro\.NETFramework\v4.5\mscorlib.Contracts.dll for ``` int String.IndexOfAny(char[] anyOf, int startIndex, int count)```
still contain: ``` System.Diagnostics.Contracts.Contract.Requires(startIndex + count < this.Length, null, "startIndex + count < Length");``` which should be: ``` System.Diagnostics.Contracts.Contract.Requires(startIndex + count <= this.Length, null, "startIndex + count <= Length");``` as it is in ``` int String.IndexOf(string value, int startIndex, int count)``` for instance.

**Comment by fedotovalex** [comment]
This is easy to fix, thanks for reporting it.

**Comment by codespare** [comment]
Great, thanks! It made for puzzling unit tests :)
