### ISSUE TITLE
Broken build due to reformatting

### ISSUE THREAD

**Issue by tom-englert** [Microsoft/CodeContracts#208]
#109 (and others) seem to break the build.
During reformatting a lot of ```this.``` statements have been removed, leaving ambiguous symbols behind:
```error CS0136: A local variable named 'exp' cannot be declared in this scope because it would give a different meaning to 'exp', which is already used in a 'parent or current' scope to denote something else```
I'm compiling with VS2013.

**Comment by tom-englert** [comment]
@sharwell does this build with VS2015?

**Comment by sharwell** [comment]
[Yes, it does.](https://ci.appveyor.com/project/sharwell/codecontracts/build/1.9.10813.40)

**Comment by sharwell** [comment]
I think the issue is limited to cases where the semantics would actually cause a build error. By that I mean either the semantics are correct in 2013 builds, or you see a CS0136 error. I'll correct these errors and everything will be :smile: again.

**Comment by tom-englert** [comment]
I wonder why they have removed CS0136 in 2015 - now writing confusing code is allowed again?
