### ISSUE TITLE
Code Contracts Abbreviators do not work if placed in a separate assembly.

### ISSUE THREAD

**Issue by voroninp** [Microsoft/CodeContracts#23]
We have moved frequent and common requirements to a separate assembly.
`Contract.Requires<ArgumentNullException>(...)` became just `Requires.NotNull(...)`. so we have fewer typing in many places. Bu then we discovered that ccrewriter does not do its job. Abbreviators are simply ignored if they are called from another assembly.

**Comment by mike-barnett** [comment]
Have you generated a contract assembly for the one containing the abbreviators? And is that contract assembly found by the rewriter when it is writing the assembly that calls the abbreviator?

Thanks,

Mike

**Comment by voroninp** [comment]
Mike, thank you. The option for building Contract Reference Assembly was `None`.
Now everything works fine.
