### ISSUE TITLE
VS2015 reports incorrect version after installing 1.9.10714.2

### ISSUE THREAD

**Issue by surekqomi** [Microsoft/CodeContracts#250]
After installing version 1.9.10714.2 (the current latest version) VS2015 (Enterprise) reports that the installed version is 1.8.10107.10 instead. This version number is also captured in the extension.vsixmanifest file in the Identity tag under the Metadata section. This incorrect version number causes VS2015 to continuously report that there is a new version available. Changing the version number in the manifest does NOT prevent VS2015 from repeatedly notifying of the "new version."

**Comment by fedotovalex** [comment]
This has been addressed in #161.

**Comment by surekqomi** [comment]
My appologies then. I searched a few times but could not get any relevant results, hence the new report.

**Comment by sharwell** [comment]
@surekqomi Duplicate reports are not a problem. Thanks for taking the time to try it out and come give feedback. :smile:
