### ISSUE TITLE
Add option to ignore missing references

### ISSUE THREAD

**Issue by GeertvanHorrik** [Microsoft/CodeContracts#261]
We are using code contracts in one of our libraries. However, it is failing because of this setup:

LibraryA => LibraryB => LibraryC

LibraryC is missing on disk (but this is expected, we are loading this at runtime at a later time). But now code contracts fails because it tries to load the assemblies too aggressively.

In order to fix this, I think an option to ignore specific errors would be great. In this case, the missing reference is never touched by any code contract, actually we don't even touch LibraryB in any of the code contracts.

I know the status of this project is a bit vague, but I am willing to create a fully working PR for this. But before I start on this, I need a few assurances:

1. Will you accept a PR that solves this issue?
2. Will you release a new version when this PR has been accepted? 

Thanks in advance!

**Comment by mike-barnett** [comment]
It is not a matter about ignoring certain errors. Unfortunately, the infrastructure that the current tools are based on require loading all (transitively) referenced assemblies. Some of the tools have already been ported to a newer version of the infrastructure, [CCI] (http://cciast.codeplex.com/), that loads only as many assemblies as it actually needs. But it would be a non-trivial amount of work to finish that porting effort. In particular, the rewriter would become even slower than it is now and people already complain a lot about how that slows down their builds.

**Comment by GeertvanHorrik** [comment]
Thanks, we appreciate the reply. Then we will have to live without CC for our library or always embed the library.
