### ISSUE TITLE
Broken build due to contracts added via PR #251

### ISSUE THREAD

**Issue by tom-englert** [Microsoft/CodeContracts#262]
PR #251 Adds some contracts which are not part of our Silverlight reference assemblies. 
According to documentation they are correct, but the CRASanitizer fails because they are not part of the Silverlight 5.0 reference assemblies.

**Comment by fedotovalex** [comment]
Good catch, thank you for fixing it.

**Comment by tom-englert** [comment]
@SergeyTeplyakov @sharwell I think I remember that Sam has setup AppVeyor for continuous integration. Does this run? I thought it would catch broken builds.

**Comment by SergeyTeplyakov** [comment]
@tom-englert I thought it should. I'll merge the PR right now.

**Comment by SergeyTeplyakov** [comment]
Merged.

**Comment by sharwell** [comment]
@tom-englert The AppVeyor build runs against my fork of the project, not against the reference repository. I don't think we'll be able to enable the automated build on the main repository until it moves to the dotnet organization.

**Comment by tom-englert** [comment]
I see, so hopefully that will happen soon :smile:

**Comment by SergeyTeplyakov** [comment]
Can this issue be closed?

**Comment by tom-englert** [comment]
Yes - just checked out master, got no build errors.
