### ISSUE TITLE
Synchronous postcondition for async generic method

### ISSUE THREAD

**Issue by SergeyTeplyakov** [Microsoft/CodeContracts#275]
ccrewrite generates special 'async closure', moves postcondition for task-based method there (both with `async` keyword and without it) and 'chains' a call to `CheckPost` from this class with resulting task.

This behavior is critical, because async postconditions should be checked only when the task completes, but the logic is wrong for async postconditions in generic methods:

```c#
class Foo
{
  public static async Task<T> FooAsync() where T: class
  {
    Contract.Ensures(Contract.Result<T>() != null);
    await Task.Delay(42);
    return default(T);
  }
}
```

In this case synchronous postcondition is emitted:

```c#
// after rewriting
class Foo
{
  public static async Task<T> FooAsync() where T: class
  {
    // some stuff generated by C# compiler
    var task = ...

   RewriterMethods.Ensure(task.Result != null, "Contract.Result<T>() != null");
    return default(T);
  }
}
```

**Comment by SergeyTeplyakov** [comment]
This bug is related to the #235 and I'll push PR with both fixes in a couple of days.

**Comment by DzheiZee** [comment]
Using 1.10.20606.1
Still encountering such defect.
Is fix for this defect included into given version (afaik it is the latest released version)
