### ISSUE TITLE
Contract on System.IO.Path.GetTempFileName

### ISSUE THREAD

**Issue by yaakov-h** [Microsoft/CodeContracts#298]
`Path.GetTempFileName` is only contracted to return non-null, however the MSDN docs say:

> This method creates a temporary file with a .TMP file extension.

Can this `Ensures` be promoted to `!string.IsNullOrWhitespace`?

**Comment by hubuk** [comment]
I have checked the situation when all 65536 possible files already exist or user does not have access to its own temp. In such scenarios GetTempFileName throws an exception.
It seems that !string.IsNullOrWhitespace is correct.
