### ISSUE TITLE
MSBuild 12.0 Microsoft.CodeContracts.targets imports wrong ContractAnalysis.targets

### ISSUE THREAD

**Issue by jbcutting** [Microsoft/CodeContracts#30]
The MSBuild v12.0 version of Microsoft.CodeContracts.targets imports $(CodeContractsInstallDir)MsBuild\v4.0\Microsoft.CodeContractAnalysis.targets. This is a relatively minor issue, but causes some problems if you're trying to add the minimum requirements for Code Contracts into your source enlistment to support builds without the extension.

The problem is on line 638 with the definition of the CodeContractAnalysisTargets property. This line is fine in the MSBuild 3.5 and 4.0 versions of the file.

The best way to resolve this would be to set the property to $(MSBuildThisFileDirectory)Microsoft.CodeContractAnalysis.targets, which would prevent the need for the version number in any of the files (4.0 and up - 3.5 doesn't support MSBuildThisFile).

Most of the content could be consolidated to avoid the need for duplicating the file with each version, but this minor change would avoid at least one problem.

**Comment by hubuk** [comment]
For now I would prefer a minor change. But, could you explain in what scenario current target path is causing problems? Is this related to build server workspace? I just want to know the nature of the problem.

**Comment by jbcutting** [comment]
It's not an issue if the entire MSBuild folder is there, but when adding to source control, it's preferable to reduce things to what's needed. Since the v12.0 file references the v4.0 folder, both folders have to be there. This would also be an issue if the 4.0 folder were removed at some point.

The simple change is to do the following, which avoids the need to worry about the version at all. This can be applied to the 4.0, 12.0, and 14.0 .targets files.

<CodeContractAnalysisTargets>$(MSBuildThisFileDirectory)Microsoft.CodeContractAnalysis.targets</CodeContractAnalysisTargets>

**Comment by sharwell** [comment]
Fixed by #57.
