### ISSUE TITLE
NullReferenceException when constructor argument used in lambda

### ISSUE THREAD

**Issue by amjrsl** [Microsoft/CodeContracts#302]
When compiling the following code with runtime checking enabled using CodeContracts 1.9.10714.2, a NullReferenceException is thrown on the Contract.Requires line:

    public class CodeContractsBugExample
    {
        private readonly object o2 = new object();

        public CodeContractsBugExample(object o1)
        {
            Contract.Requires(o1 != null);

            Func<string> a = () => o1.ToString();
        }

        static void Main(string[] args)
        {
            var a = new CodeContractsBugExample(new object());
        }
    }

Looking at the generated code it looks like the display class is never being instantiated before it is accessed:

```
public CodeContractsBugExample(object o1)
{
    CodeContractsBugExample_<>c__DisplayClass1_0_0 class__;
    __ContractsRuntime.Requires(class__.o1 > null, null, "o1 != null");
    this.o2 = new object();
    Func<string> func = () => o1.ToString();
}
```

If the initialization of the read-only o2 field is removed, then the display class is instantiated correctly:

```
public CodeContractsBugExample(object o1)
{
    CodeContractsBugExample_<>c__DisplayClass1_0_0 class__ = new CodeContractsBugExample_<>c__DisplayClass1_0_0 {
        o1 = o1
    };
    __ContractsRuntime.Requires(class__.o1 > null, null, "o1 != null");
    Func<string> func = () => o1.ToString();
}
```

**Comment by fedotovalex** [comment]
This looks like a duplicate of #191.

**Comment by amjrsl** [comment]
Agreed - this looks like the same issue.
