### ISSUE TITLE
CodeContracts prevents build completion with embedded resource assembly

### ISSUE THREAD

**Issue by Leggless** [Microsoft/CodeContracts#312]
We are building a visual studio 2012 c# project with code contracts support enabled that references a library with an embedded resource assembly.  The build fails as code contracts requires the assembly that is embedded as a resource in order to build.

There is a workaround by adding the embedded assembly to the project. If the referenced library is self contained, why should the project need to provide access to the embedded assembly as well?

We are hoping that there is a fix available so that the workaround is no longer required.

**Comment by hubuk** [comment]
@Leggless Is the embedded resource assembly referenced by the project or is it being used via reflection only? A simple project that presents the problem would be really helpful.

**Comment by Leggless** [comment]
@hubuk, The project A that embeds the assembly B also references B, but all other projects C,D,E... that uses the project A needs access to B to compile using code contracts.
Project A uses the OnAssemblyResolve to use the embedded assembly in memory .

Code Contracts was reporting the following in the output log
  Reading assembly 'A' from 'Apath\bin\Release\A.dll' resulted in errors.
  	Assembly reference not resolved: B, Version=0.0.0.0, Culture=neutral, ...
  	Could not resolve type reference: [B]BInterface.
ccrewrite : error : Rewrite aborted due to metadata errors. Check output window
  elapsed time: 3.0384ms
C:\Program Files\Microsoft\Contracts\MsBuild\v4.0\Microsoft.CodeContracts.targets(255,5): error MSB3073: The command ""C:\Program Files\Microsoft\Contracts\Bin\ccrewrite.exe" "@Dccrewrite.rsp"" exited with code -1.

**Comment by hubuk** [comment]
@Leggless This is a known limitation. Already reported in #261.
Fix for this may require some more work. I think we can leave this issue open until fixed.

**Comment by Leggless** [comment]
OK thanks for the quick response.
