### ISSUE TITLE
Error: Could not load file or assembly Microsoft.Build.Utilities.v3.5

### ISSUE THREAD

**Issue by andriysavin** [Microsoft/CodeContracts#353]
Steps:
1. Have a PC with newest tools installed (I have VS2015, .Net 4.6.x, Win10, no legacy VS or framework 3.5);
2. In VS create a console app project;
3. Enable full contracts checking;
4. Build the project;
5. Observe the error: The "Microsoft.Research.CodeContractsAnalysis" task could not be loaded from the assembly C:\Program Files (x86)\Microsoft\Contracts\Bin\MsBuildCodeContracts.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v3.5, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.	ConsoleApplication3	C:\Program Files (x86)\Microsoft\Contracts\MsBuild\v14.0\Microsoft.CodeContractAnalysis.targets	 238

**Comment by andriysavin** [comment]
Seems to be fixed in v.1.10.10126.2-rc1

**Comment by hubuk** [comment]
I was about to write:)
Reference to Microsoft.Build.Utilities.v3.5 has been removed from MsBuildCodeContracts.dll in 1e0abeef. New pre-release version has now updated reference to v4.0

**Comment by andriysavin** [comment]
That's great, thanks! However, I think its not cool that there is such a dependency on concrete tools version. Probably, it would be a good approach to have all dependencies installed as NuGet packages. Not sure is this is technically possible though.

**Comment by SergeyTeplyakov** [comment]
@andriysavin Current solution is tightly coupled with preinstalled version of msbuild, just because up until now MSBuild installation was a prerequisite for almost any .NET-related development. Currently things are changing and it would be possible in the near future to pull MSBuild from the nuget and remove current installation requirements.

**Comment by andriysavin** [comment]
That would be exactly what I dream about! :)
