### ISSUE TITLE
rewrite is incorrect for methods using yield return

### ISSUE THREAD

**Issue by mistoll** [Microsoft/CodeContracts#378]
When using
`Contract.Ensured(Contract.Result<IEnumerable<...>>() != null)`
in a method which uses yield return an ContractException is thrown at runtime.

Code Contracts Version: 1.8.10107.10
Exception text: 
> (free translation) An Assembly (...) must be written using Code Contracts Binary Rewriter (CCRewrite). It calls Contract.Ensures and defined the CONTRACTS_FULL symbol. Remove all explicit definitions of the CONTRACTS_FULL symbol and rebuild it. ...

**Comment by yaakov-h** [comment]
Does this follow the same case as #321, or this a new way to trigger the bug?

**Comment by mistoll** [comment]
IMO, this is a dublicate. 

Going to test the fix and reopen if it's not fixed.
