### ISSUE TITLE
Emits gibberish into XML documentation

### ISSUE THREAD

**Issue by NameOfTheDragon** [Microsoft/CodeContracts#388]
When the setting `Emit contracts into XML documentation `is enabled, and the documentation is compiled with Sandcastle (Sandcastle Help File Builder), the emitted contracts are gibberish.

Example code:  

    [ContractClassFor(typeof(ISpecification<>))]
    abstract class ISpecificationContract<TEntity> : ISpecification<TEntity> where TEntity : class
        {
        public bool IsSatisfiedBy(TEntity entity)
            {
            Contract.Requires(entity != null);
            throw new System.NotImplementedException();
            }
        }

Documentation produced:
![badcontracts](https://cloud.githubusercontent.com/assets/1268490/13213879/de33db54-d943-11e5-8ef4-fd59ea6d199d.PNG)

**Comment by hubuk** [comment]
@NameOfTheDragon Is the result produced by the latest version of Code Contracts (v.1.10.10126.2-rc1)?
Similar issue has been reported in #307 and should be fixed in RC1.

**Comment by NameOfTheDragon** [comment]
@hubuk Good point - I hadn't noticed that build (I'm currently using a private build that is a few weeks old). I will try it and report back.

**Comment by NameOfTheDragon** [comment]
Indeed, it does seem to be working better now!
![image](https://cloud.githubusercontent.com/assets/1268490/13215558/12c12bce-d94e-11e5-8167-59a5ec7c4e06.png)
Arguably, the `(object)` cast is a bit "noisy" but I guess it does no harm, so I am closing the issue.

While I'm at it, I want to say a massive THANK YOU to all the people working hard keeping this project alive. I've looked at various other offerings but nothing does the job as well as Code Contracts. Good work everyone!
