### ISSUE TITLE
Cannot build anymore with Json.NET portable.

### ISSUE THREAD

**Issue by ioancrisan** [Microsoft/CodeContracts#389]
I get in the latest days an exception when building my portable project referencing the Json.NET package. Here is a part of the build log:

5>Task "Exec" (TaskId:37)
5>  Task Parameter:WorkingDirectory=obj\Debug\ (TaskId:37)
5>  Task Parameter:Command="C:\Program Files (x86)\Microsoft\Contracts\Bin\ccrewrite.exe" "@Kephas.Serialization.Jsonccrewrite.rsp" (TaskId:37)
5>  "C:\Program Files (x86)\Microsoft\Contracts\Bin\ccrewrite.exe" "@Kephas.Serialization.Jsonccrewrite.rsp" (TaskId:37)
5>  Reading assembly 'Newtonsoft.Json' from 'D:\Quartz\kephas-git\kephas\src\packages\Newtonsoft.Json.8.0.2\lib\portable-net40+sl5+wp80+win8+wpa81\Newtonsoft.Json.dll' resulted in errors. (TaskId:37)
5>  	Could not resolve type reference: [mscorlib]System.Reflection.BindingFlags. (TaskId:37)
5>ccrewrite : error : Rewrite aborted due to metadata errors. Check output window
5>  elapsed time: 418,8431ms (TaskId:37)
5>C:\Program Files (x86)\Microsoft\Contracts\MsBuild\v14.0\Microsoft.CodeContracts.targets(265,5): error MSB3073: The command ""C:\Program Files (x86)\Microsoft\Contracts\Bin\ccrewrite.exe" "@Kephas.Serialization.Jsonccrewrite.rsp"" exited with code -1.
5>Done executing task "Exec" -- FAILED. (TaskId:37)
5>Done building target "CodeContractRewrite" in project "Kephas.Serialization.Json.csproj" -- FAILED.: (TargetId:61)

I see that there are others having the same problem, but I didn't find any answer so far. Could you hint me something I can do for ccrewriter to exclude the Newtonsoft.Json.dll from analysis?
See also http://stackoverflow.com/questions/30965708/portable-library-doesnt-build-with-code-contracts.

Thanks in advance!

**Comment by hubuk** [comment]
@ioancrisan Hi,
Here is a similar issue reported on Newtonsoft.Json project page:
https://github.com/JamesNK/Newtonsoft.Json/issues/626
I would need to dig into portable libraries to understand how the references are resolved at runtime.
There is a mscorlib in version 2.0.5.0 referenced by .NET 4.0 PCL Newtonsoft.Json but at runtime version 4.6.* is loaded.
ccrewrite searches for 2.0.5.0 which it fails to find I think.

Changing to 4.5 PCL should help as a workaround.

**Comment by ioancrisan** [comment]
Thanks for pointing out this to me. Unfortunately I didn't find a way for nuget to choose the net45 PCL, but a manual reference change did the trick. For a workaround I can live with it.
