### ISSUE TITLE
Static checker considers `Enum` as reference type instead of value type

### ISSUE THREAD

**Issue by coldacid** [Microsoft/CodeContracts#394]
I have an extension method on `Enum` that allows me to get an attribute set on a provided enumeration value:

```csharp
public static T GetAttribute<T>(this Enum value) where T : System.Attribute
{
    var type = value.GetType();
    var memberInfo = type.GetMember(value.ToString());
    var attributes = memberInfo[0].GetCustomAttributes(typeof(T), false);
    return attributes.Length > 0 ? (T)attributes[0] : null;
}
```

Ignoring that I should be checking to ensure that the value is a defined one for the enumeration, the static checker warns me that I should add a precondition `value != null`. Seeing that enumeration types are always value types instead of reference types, though, `value` will never be null.

The checker should recognize that System.Enum as a parameter would be a value, not a reference, and not tell me `Enums.cs(99,13): warning : CodeContracts: Missing precondition in an externally visible method. Consider adding Contract.Requires(value != null); for parameter validation`

**Comment by SergeyTeplyakov** [comment]
@coldacid Actually, cccheck is absolutely correct here. Concrete enum types are indeed values, but `System.Enum` is a reference type.

For instance, here you can get `NullReferenceException`:

```csharp
Enum @enum = null;
@enum.GetAttribute<System.Attribute>();
```

**Comment by coldacid** [comment]
Ugh, really? Even though it's derived from `System.ValueType`?

**Comment by federicoce-moravia** [comment]
ValueType is also a reference type. It overrides System.Object methods with more sensible implementations for value semantics.

**Comment by coldacid** [comment]
And of course I can't use a type param constrained to `enum` because that's not supported. Guess I'll just have to check for `null` then. :(

**Comment by federicoce-moravia** [comment]
Check the "EnumUtils" class in this SO question:
http://stackoverflow.com/questions/1424971/parse-string-to-enum-type

I use that to great effect in our projects.

**Comment by coldacid** [comment]
I'll give that a shot, thanks.
