### ISSUE TITLE
Support VS2013 for CC Editor Extensions

### ISSUE THREAD

**Issue by reitzmichnicht** [Microsoft/CodeContracts#4]
Editor Extensions throw an exception when only VS2013 is installed on a machine. Please provide a new extension that supports VS2013.

Even when registering the missing VS2012 dlls in the GAC the intellisense support to show contracts doesn't work.

**Comment by aarondandy** [comment]
If somebody has a machine that reproduces this could they provide a Fusion Log for the failed bind, assuming it is a failed bind.

**Comment by sharwell** [comment]
This is something I can probably take a look at, but it could be a few days.

**Comment by reitzmichnicht** [comment]
Microsoft.VisualStudio.Csharp.Services.Language.dll is the dll it tries to load from VS2012

**Comment by reitzmichnicht** [comment]
Corresponding forum post:
https://social.msdn.microsoft.com/Forums/en-US/a79a3a31-ef22-4946-8b00-9953c2d57617/code-contracts-editor-extensions-on-vs-2013-rtm-crash?forum=codecontracts

**Comment by sharwell** [comment]
@reitzmichnicht Thanks for that update. I've worked with this DLL successfully in a single VSIX which supports Visual Studio 2010 through 2015:

https://github.com/tunnelvisionlabs/InheritanceMargin

**Comment by Daniel-Svensson** [comment]
@sharwell Have you made any progress with VS 2013 support?
I would definitly love support for VS 2013 (and maybe 2015)
