### ISSUE TITLE
Cannot remove CC v1.8 (to upgrade to v1.9)

### ISSUE THREAD

**Issue by zerkms** [Microsoft/CodeContracts#406]
It's currently the v1.8.10107.10 installed in my VS Community Edition, and even though I download the latest installer for the v1.9.10714.2 and run it - the version installed is still v1.8.

I cannot even remove the older one: I run the installers "Remove" option and after it completes successfully - the extension is still in the VS.

How would I resolve that?

**Comment by davidhesselbom** [comment]
You're not the first person to be bothered by this! See #161. 

I don't know the developers don't simply make a new version where the version number is correct...

**Comment by zerkms** [comment]
@davidhesselbom thanks for the reference!
