### ISSUE TITLE
upgrade from 1.8.10107.10 seems not possible at all

### ISSUE THREAD

**Issue by csizo** [Microsoft/CodeContracts#411]
I am stucked with upgrading from the 1.8.10107.10 release...

vs 2015 sp[1-2] still reminds me to upgrade. 
I am always downloading the most recent release. 
Installing... Then still have the same issue. 

Do you have any workaround? Is this a known issue?

Thanks in advance!
Regards
zcs

**Comment by michaelvolz** [comment]
You can fix this by following the steps outlined in this ticket:
https://github.com/Microsoft/CodeContracts/issues/161#issuecomment-165949263

**Comment by csizo** [comment]
Perfect. Than you!
