### ISSUE TITLE
Wrong version in VS2015?

### ISSUE THREAD

**Issue by zyrconium13** [Microsoft/CodeContracts#415]
I just installed Code Contracts version 1.9.10714.2 having VS2015 installed as well, but inside VS2015 it displays as version 1.8.10107.10 instead. It displays the correct version inside VS2013 though.

Is this by design or is this a bug? Or are there two versions (for VS2013 and VS2015) only packaged inside the same installer?

**Comment by Reonekot** [comment]
Known issue, look fx at https://github.com/Microsoft/CodeContracts/issues/411
