### ISSUE TITLE
Reuse of existing local variable 'key' in contract.	

### ISSUE THREAD

**Issue by ilmaslennikov** [Microsoft/CodeContracts#416]
I'm getting strange error 'Reuse of existing local variable 'key' in contract.' while compiling following code: 

        public void SplitChild(int index, int newNodeId)
        {
            Contract.Requires(2 * Degree == СhildNodesCount);
            Contract.Requires(index < СhildNodesCount);
            Contract.Requires(index > 0);
            var z = new BTreeNode(true, newNodeId, _t, _btreeStorage);
            var y = _btreeStorage.DiskRead(_nodes[index]);
            z._isLeaf = y._isLeaf;
            z._keys = new int[_t - 1];
            z._nodes = new int[_t];
            for (int j = 0; j < _t - 1; j++)
            {
                z._keys[j] = y._keys[j + _t];
            }
            if (!y._isLeaf)
            {
                for (int j = 0; j < _t; j++)
                {
                    z._nodes[j] = y._nodes[j + _t];
                }
            }
            var key = y._keys[_t - 1];
            Array.Resize(ref y._nodes, _t);
            Array.Resize(ref y._keys, _t - 1);
            Array.Resize(ref _keys, _keys.Length + 1);
            Array.Resize(ref _nodes, _nodes.Length + 1);
            for (int j = _nodes.Length - 2; j > index; j++)
            {
                _nodes[j + 1] = _nodes[j];
            }
            _nodes[index + 1] = z.Id;
            for (int j = _keys.Length - 2; j > index - 1; j++)
            {
                _keys[j + 1] = _keys[j];
            }
            _keys[index] = key;
            _btreeStorage.DiskWrite(y);
            _btreeStorage.DiskWrite(z);
            _btreeStorage.DiskWrite(this);
            Contract.Ensures(y.CheckNodes() && y.CheckKeys());
            Contract.Ensures(CheckNodes() && CheckKeys());
            Contract.Ensures(z.CheckNodes() && z.CheckKeys());
        }

**Comment by michaelvolz** [comment]
`Contract.Essures(...)` should be placed at the begin of the method together with the `Contract.Requires(...) statements. I know It is counter intuitive, but the assembly will be rewritten and those checks will end at the right place.

**Comment by ilmaslennikov** [comment]
michaelvolz Thank you for your response, but in case of my method I need check object invariants for new objects x and y. If I place 
        Contract.Ensures(y.CheckNodes() && y.CheckKeys());
        Contract.Ensures(CheckNodes() && CheckKeys());
        Contract.Ensures(z.CheckNodes() && z.CheckKeys());
at the beginning of the method, then I got compilation error:
Cannot use local variable 'y' before it is declared

**Comment by AlexanderTaeschner** [comment]
In this case you have to use Contract.Assume at the end of your method.
If CheckNodes() && CheckKeys() has to be always true in your object, you can additional add Contract.Invariant in the ContractInvariantMethod method of your object.

**Comment by yaakov-h** [comment]
@ilmaslennikov how can you have an invariant for a local variable (z and y)? I'd think an ensures on a local variable ought to be invalid.
