### ISSUE TITLE
Define "global" Code Contracts for legacy or 3rd party libraries that do not use Code Contracts

### ISSUE THREAD

**Issue by cofiem** [Microsoft/CodeContracts#421]
I've been working a lot recently with libraries that do not use Code Contracts. This works fine, but I'm getting lots of suggested `Contract.Assume`.

As far as I can see, I have to add these in all over my code, each time I use a legacy or 3rd party class/method/whatever.

Is there a way to specify, _in a single location only_, the contracts for a library? This could then be used everywhere, removing the need for the many suggested `Contract.Assume` outputs and making my code much more robust.

I have seen references to people manually creating the outputs from the code contract rewriter to get this functionality. I'd rather not re-invent the wheel by manually creating the output Code Contracts should be generating.

Does something like this already exist? If not, could this be considered?

**Comment by yaakov-h** [comment]
The rewriter generates for your own contracted assemblies when you set "Contract Reference Assembly" to "Build".

For anything else you need to either assume, or create your own Reference Assembly. This is what Code Contracts provides for the .NET Framework [here](https://github.com/Microsoft/CodeContracts/tree/master/Microsoft.Research/Contracts).

**Comment by cofiem** [comment]
Thanks @yaakov-h. It looks like it's a copy of the code, with just the properties/methods and code contracts, without all the attributes and implementation?

**Comment by yaakov-h** [comment]
Pretty much. It's the same as you'd build when contracting an interface or a method on an abstract class.

**Comment by cofiem** [comment]
Excellent. That I can do. Thanks for pointing me in the right direction.
