### ISSUE TITLE
Visual Studio 2015 defines CONTRACTS_FULL even if Code Contracts are not installed.

### ISSUE THREAD

**Issue by quixoticaxis** [Microsoft/CodeContracts#427]
If you call contracts' methods from your code in Visual Studio 2015 Community Edition without code contracts installed, the program fails on the first call. And I couldn't find a way to undefined CONTRACTS_FULL.
Am I missing something? I thought Code Contracts could be used without both static checker and runtime checker as a way to document your code.

**Comment by yaakov-h** [comment]
Are you using `Contract.Requires<TException>(...)`? This call requires a rewriter. Other calls (e.g. `Contract.Requires(...)` and `Contract.Ensures(...)`) are conditional on `CONTRACTS_FULL`.

**Comment by quixoticaxis** [comment]
Yes, I was using Contract.Requires<TException>(...). Thank you.

The error message is vague though. It speaks of CONTRACTS_FULL being defined, so my first thought was that I somehow initiated the definition of symbol without noticing it or it was defined by default.
