### ISSUE TITLE
Update Problem VS2015 (1.8.10107.10  -> 1.9.10714.2)

### ISSUE THREAD

**Issue by mph911** [Microsoft/CodeContracts#440]
`Code Contratcs for .NET` displays a needed update. After installing the update it continues to show the message and dispite the update from `1.8.10107.10` -> `1.9.10714.2` the old version number is displayed!

Un-install, reboot and re-install does not change the situation. 

As an assist I have `Code Contracts Tool` installed. Unistall that and then install `Code Contracts` does not change anything either.

>VS Professional 2015 14.0.25123.00 Update 2

How to solve this issue!

**Comment by yaakov-h** [comment]
This is as known issue. See #411/#161.

**Comment by mph911** [comment]
Solved the problem!
Cheers
