### ISSUE TITLE
Code Contracts Rewriter creates invalid assembly references

### ISSUE THREAD

**Issue by Alois-xx** [Microsoft/CodeContracts#450]
When an assembly is rewritten the assembly reference flags to all reference assemblies still contain 0x70 in their flags which can cause spurious runtime exceptions in the form of InvalidCastExceptions. 

You need to decompile the rewritten binary with Mono Cecil or similar tools to see the wrongly encoded assembly references for reference assemblies. 

See https://aloiskraus.wordpress.com/2016/07/18/the-non-contracting-code-contracts/ for more information.

Yours,
   Alois Kraus

**Comment by Daniel-Svensson** [comment]
This might explain why we have been getting similar error messages in the Visual Studio designer (causing it to crash).

**Comment by piedar** [comment]
This can be closed now, right?  Would be nice to bump the NuGet package to include the fix.

**Comment by Alois-xx** [comment]
The change should fix the issue.
