### ISSUE TITLE
Rosalyn Code Analyzer for Code Contracts Usage

### ISSUE THREAD

**Issue by normanhh3** [microsoft/CodeContracts#485]
Hi Folks,

Has anyone here considered creating a Rosalyn Code Analyzer that provides rules / fixes for ensuring code contracts are being properly added / crafted to a project?

**Comment by yaakov-h** [comment]
How would you define "properly" and what benefit would this have over simply observing the static checker errors?

**Comment by normanhh3** [comment]
The thing I am looking for is guidance for new developers to the project in
how to add the basic boilerplate contract specifications.

Something along the lines of: All Public Classes should have pre and post
condition checks.

Another: All classes with state should have an invariant check defined.

Another might be: All Public interfaces should be decorated with a contract
class specification attribute.

Ultimately, I would love for a new developer to be able to see these, have
quick access to a list of fixes that start them down the implementation
path towards returning contract value quickly.

**Comment by tom-englert** [comment]
You could use this as a base: https://github.com/tom-englert/ContracsReSharperInterop

It has a slightly different purpose, since it tries aligning the contracts with R# attributes, but you can get the basic idea from it how to add the contracts.

**Comment by normanhh3** [comment]
Looks like the existing static analyzer will get me 80% of the way to what I want.  I'm still interested in seeing the static analyzer converted to use Roslyn *so that* quick fixes can be used to quickly add suggested constraints for example that are immediately compilable for cases where full information is available (i.e. null checking).

For now the static analysis works just fine.
