### ISSUE TITLE
NullReferenceException with lambda in requires of contract class in VS2015

### ISSUE THREAD

**Issue by billings7** [Microsoft/CodeContracts#49]
Ccrewrite fails with a NullReferenceException when a contract class contains a requires that has a lambda expression when compiled in Visual Studio 2015.

For example:
```c#
[ContractClass(typeof(FooContracts))]
public interface IFoo
{
    void Method(params string[] strings);
}

[ContractClassFor(typeof(IFoo))]
public abstract class FooContracts : IFoo
{
    public void Method(params string[] strings)
    {
        Contract.Requires(Contract.ForAll(strings, s => s.Length > 0));
    }
}

public class Foo : IFoo
{
    public void Method(params string[] strings)
    {
        Console.WriteLine(string.Join(", ", strings));
    }
}
```

Perform Runtime Contract Checking has to be enabled and not None.

I believe it is due to a change in how lambdas and closures are compiled by Rosyln. Something that may be related is a Debug.Assert failing in [Foxtrot\Foxtrot\Utility.cs line 2320](https://github.com/Microsoft/CodeContracts/blob/master/Foxtrot/Foxtrot/Utility.cs#L2320)

**Comment by SergeyTeplyakov** [comment]
Maybe this is related to #72. I'll add test case and test it withing my Roslyn fix.

**Comment by SergeyTeplyakov** [comment]
I've added test case in my working branch that support VS14 and I didn't get any issues.

**Comment by SergeyTeplyakov** [comment]
This bug is still active! Reproduced in VS2015 (strange, that it was not reproduced at unit tests)!

**Comment by SergeyTeplyakov** [comment]
The root cause of this issue that roslyn-based compliler started generating new names for closures classes. Before the name always was <>c__DisplayClass0 and now I see only <>c.

I send an email to Roslyn guys asking about this new behavior. If this is a final behavior, we need to change rewriter, otherwise it will work as is.

**Comment by SergeyTeplyakov** [comment]
And the bug is not reproducable in unit tests because I've got roslyn-based compiler with "correct" (i.e. old behavior).

**Comment by sharwell** [comment]
@SergeyTeplyakov Label as fixed?

**Comment by SergeyTeplyakov** [comment]
Sure. Will check all the closed bugs with fixed.
