### ISSUE TITLE
Alternative active fork

### ISSUE THREAD

**Issue by vbaderks** [Microsoft/CodeContracts#56]
Hi,

The offical codecontracts repository seems not to be maintained anymore. Is there an alternative fork that is maintained and moved forward?

Victor

**Comment by aarondandy** [comment]
If you submit your PR to this repository they will likely be picked up by other developers and merged into their working branches. There is no official fork although each person working on the project technically has a fork of it. Microsoft has not abandoned the project but is working getting back into a more active role on it. The network graph shows the current state of things: https://github.com/Microsoft/CodeContracts/network

**Comment by Suchiman** [comment]
@aarondandy what leads you to this conclusion? All i see is microsoft pushed their internal source, applied on 2 days in january community pull requests and on 3 days in february a few another community pull requests. After that there have been many more pull requests from the community which are neither answered nor pulled and everything i can see on the network graph is community activity.

**Comment by mike-barnett** [comment]
We (the people in Microsoft who are still working on the Code Contracts code) are very sorry about how slow we’ve been responding to things. We definitely plan to accept the pull requests that are outstanding and are currently working on some of the issues about Roslyn-generated binaries. We hope to have more information soon.

Mike

**Comment by Suchiman** [comment]
Thanks for the offical statement @mike-barnett , i'll keep watching for news then :+1:

**Comment by sharwell** [comment]
@SergeyTeplyakov This can be closed; it's answered by #59 and #62.
