### ISSUE TITLE
Create a new set of lables for project.

### ISSUE THREAD

**Issue by hubuk** [Microsoft/CodeContracts#64]
What do you think about creating a new sot of labels for CC? Current one does not look consistent.
Newly created set may be similar to the one defined for [NuGet](https://github.com/NuGet/Home/labels).

**Comment by sharwell** [comment]
I've been using [this set of labels](https://github.com/tunnelvisionlabs/dotnet-trees/blob/master/CONTRIBUTING.md#labels) for the StyleCopAnalyzers project. This project will certainly require a few unique labels as well:

* Missing reference contracts
* Erroneous reference contracts

**Comment by sharwell** [comment]
@SergeyTeplyakov I think this can be closed. The labels are likely to evolve over time, but this is a start.
