### ISSUE TITLE
CCRewrite fails with NRE on async method with Ensures.ForAll with captured params

### ISSUE THREAD

**Issue by SergeyTeplyakov** [Microsoft/CodeContracts#69]
Code contracts repo has a bunch of tests for async methods. Unfortunately, some of them are broken.

For instance, tests for `async6.cs` to `async9.cs` will fail because ccrewrite.exe will return -1.

Here is a small repo for the issue:

```c#
class TestTaskContracts
{
    public async Task<List<int>> FooAsync(int limit)
    {
        Contract.Ensures(Contract.ForAll(Contract.Result<List<int>>(), i => i < limit));

        await Task.Delay(42);

        return Enumerable.Range(1, 10).ToList();
    }
}
```

Running ccrewrite on this class will fail with `NullReferenceException` at System.Compiler.Writer.cs line 1814.

**Comment by sharwell** [comment]
@SergeyTeplyakov Label fixed instead of up for grabs?

**Comment by SergeyTeplyakov** [comment]
Done.
