### ISSUE TITLE
Update/uninstall leaves VS2013 extension behind

### ISSUE THREAD

**Issue by cremor** [Microsoft/CodeContracts#7]
If you uninstall code contracts, either manually or by installing a new version, the VS2013 extension stays installed or stays at the old version. The whole folder C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\Extensions\Microsoft\CodeContracts isn't removed.

**Comment by reitzmichnicht** [comment]
I can confirm this.Happens on every update in VS2013.4

**Comment by icnocop** [comment]
This causes Visual Studio to indicate that there's an update to the Code Contracts for .NET extension even though the latest version is installed.
For example:
Current Version: 1.7.11106.10
New Version: 1.7.11202.10

In this case, there's a directory for both versions in that folder:
C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\Extensions\Microsoft\CodeContracts\1.7.11106.10
C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\Extensions\Microsoft\CodeContracts\1.7.11202.10

For reference, see the following:
http://stackoverflow.com/questions/27914824/code-contracts-version-does-not-updated

Thank you.

**Comment by tom-englert** [comment]
This still happens with  1.9.10714.2

**Comment by federicoce-moravia** [comment]
Same here. This confuses VS a great deal, misreporting the version number unless you remove the folder(s) and touch the extensions.configurationchanged file.

It may be related, I've noticed the install/repair/uninstall process takes a suspicious amount of time, the progress bar getting stuck at about 80% as if it was wrestling against a file in use or something similar.

**Comment by sharwell** [comment]
> It may be related, I've noticed the install/repair/uninstall process takes a suspicious amount of time, the progress bar getting stuck at about 80% as if it was wrestling against a file in use or something similar.

This is calls to **devenv /setup**. Unfortunately not avoidable when you manually install extensions (e.g. use MSI instead of just having the user open a VSIX).

**Comment by tom-englert** [comment]
Yes, **devenv /setup** is very slow. 
However the installer calls **devenv /setup** while the old extension is still there. The installer should first remove the old version, then call **devenv /setup**.

**Comment by sharwell** [comment]
@tom-englert Yes that is correct. My comment was only meant to clarify that the "hang" isn't the problem here; failing to remove the extension files is.

**Comment by tom-englert** [comment]
@sharwell 
> This is calls to devenv /setup. Unfortunately not avoidable when you manually install extensions (e.g. use MSI instead of just having the user open a VSIX).
I did not look into details how the extension is installed, but packing the VSIX into the MSI and just call the VsixInstaller.exe as a custom action could simplify the installation, fix issues with left-behind versions and speed up the installation.

**Comment by sharwell** [comment]
@tom-englert Eventually the best possible experience would be an installation that only required VSIX and NuGet. As long as the MSI is used, we'll be fine as long as it properly detects installed versions and knows how to remove itself (both of which should now be in place).

**Comment by tom-englert** [comment]
@sharwell it was just an idea - however never change a running system :smile:

**Comment by Angeland** [comment]
Reopen. This issue is still here. asking for the update in VS after uninstall it still asks. after the vs extensions codecontract folder is removed it STILL asks for update.

**Comment by joemey** [comment]
I too have the problem with the wrong version number and it looks like the problem ist that for VS 2015 the current installer contains a wrong extension.manifest file (V14extension.manifest in the msi package) with the version 1.8.10107.10.
The manifest files for V10, V11, V12 are correct.

**Comment by Fabman08** [comment]
@joemey same problem too

**Comment by quixoticaxis** [comment]
@joemey same problem with VS2015 Update 2.

**Comment by hickford** [comment]
Is this fixed in the strong sense "new versions tidy up after old versions" or only in the weak sense "new versions don't leave any mess of their own"?

I followed http://stackoverflow.com/a/27914825/284795 to cleanup Code Contracts on my computer

**Comment by thegreatco** [comment]
I had to manually edit the manifest file to update the version listed in VS2015
