### ISSUE TITLE
Installer creates a C:\VS11Root folder

### ISSUE THREAD

**Issue by cremor** [Microsoft/CodeContracts#8]
Whenever I install Code Contracts, the installer creates a C:\VS11Root folder that seems to contain the Visual Studio extension. This happens with machines where VS2010 or VS2013 is installed (haven't tested VS2012).

**Comment by sryze** [comment]
I noticed this too. Shouldn't [this](https://github.com/Microsoft/CodeContracts/blob/180c3ae426fae1c31105fc672eeba57c91f76ed0/Microsoft.Research/ManagedContract.Setup/ManagedContracts.wxs#L263) be `<DirectoryRef Id="VS11_ROOT_FOLDER">`?

**Comment by sharwell** [comment]
I have a pretty good idea how to fix this - I had to do it for another MSI I created.

**Comment by billings7** [comment]
@sharwell I'm not a wix expert, but could it be that the id in [ManagedContracts.wxs line 249](https://github.com/Microsoft/CodeContracts/blob/master/Microsoft.Research/ManagedContract.Setup/ManagedContracts.wxs#L249) is the same as the value passed to Condition a few lines below? Its the same for VS10 and VS11, but VS12 and VS14 use VSXX_ROOT_FOLDER_EXISTS for the condition instead.

**Comment by yaakov-h** [comment]
Good point.

VS12 and VS14 use `<![CDATA[Installed OR VSXX_ROOT_FOLDER_EXISTS]]>` whereas VS10 and VS11 use `VS10_ROOT_FOLDER`.
