### ISSUE TITLE
Static checker fails with "Cannot connect to the cache" on VS2015

### ISSUE THREAD

**Issue by SergeyTeplyakov** [Microsoft/CodeContracts#80]
I was able to build and run ccrewriter on VS2015, but got following failure when I tried to run cccheck:

```
CodeContracts: ConsoleApplication1: Time spent trying to connect to the cache server: 00:00:00.0156274
CodeContracts: ConsoleApplication1: Diagnostic: Failed to connect to any cache.
(1,1): warning : CodeContracts: System.Diagnostics.Contracts.ContractDeclarativeAssemblyAttribute.#ctor()[0x6]: Cannot connect to the cache. The CodeContracts static check will not run
CodeContracts: ConsoleApplication1: 
CodeContracts: ConsoleApplication1: Background contract analysis done.
```

Disableing 'Cache results' options for Static Checking fixes the issue, but by default this option turned on.

Maybe the root cause of the issue, that following dbname is used for local cache: `(LocalDb)\v11.0`.

**Comment by tom-englert** [comment]
I also had frequent problems with the LocalDb cache, if the file is gone but still registered with SqlServer it's not easy to recover. 
Maybe you can have a look at https://github.com/tom-englert/CodeContracts/commit/76ed1a3350173f6fafc78f78e81ef68cf6305f21, this solved all my problems.

**Comment by SergeyTeplyakov** [comment]
I solved this problem by changing connection string from (LocalDb)\11.0 to (LocalDb)\MSSQLLocalDB.

**Comment by tom-englert** [comment]
Most people would be lost if the cache does not work out of the box. We should definitely improve cache handling.

**Comment by SergeyTeplyakov** [comment]
I do have a fix that uses new connection string but falls back to the previous one if it fails. 

And we definitely can (and should) improve this experience! :+1:

**Comment by tom-englert** [comment]
Just being curious: Where does the "MSSQLLocalDB" come from? Is the a new standard with the newer SQLServers?

**Comment by SergeyTeplyakov** [comment]
Yep, this is different names for different sql server compact version.

For sql server 2012 compact is (LocalDb)\11.0 and for Sql server 2014 compact is (LocalDB)\MSSQLLocalDB.

And on VS2015 there is no 2012 version that's why old code fails.

**Comment by tom-englert** [comment]
So how does this affect performance? Trying through all possible DB-Names might be a time consuming task. 
When I enter a wrong name in the SQL Management Strudio it takes about 10sec until it returns with an error. 
Once the connection succeeds we probably need to cache the name.

**Comment by SergeyTeplyakov** [comment]
It won't affect performance. It affects correctness. CCCheck just fails on VS2015 machine.

And it will slow down a little bit, but only on the old machine without VS2013/VS2015. Current logic is following: it checks for the first available local connection and stops seeking for others. I can change the logic to do this in parallel, but minor performance degradation with my fix would be only for old boxes (VS2012) but we can improve this in the future.

**Comment by taschna** [comment]
This problem is not solved yet! I just build the project using VS2015 and get the following error message:
```
CodeContracts: TestLibrary: Time spent trying to connect to the cache server: 00:00:01.1990698
CodeContracts: TestLibrary: Diagnostic: Failed to connect to any cache.
(1,1): warning : CodeContracts: System.Diagnostics.Contracts.ContractDeclarativeAssemblyAttribute.#ctor()[0x6]: Cannot connect to the cache. The CodeContracts static check will not run
CodeContracts: TestLibrary: 
CodeContracts: TestLibrary: Background contract analysis done.
```
Unfortunately I am not sure how to debug this, otherwise I would be happy to help.
